### ISSUE TITLE
Watcher doesnt update components

### ISSUE THREAD

**Issue by Nikkiez** [mjmlio/mjml-component-boilerplate#11]
The gulp-watch watcher includes the glob "components/**.js". So the components should be updated by changing the source code of a component. Currently the changes never appear while the watcher ist runnig, only if I restart the watcher. (npm start)

It seems that the import line for the component(s) never update the content. So during the runtime of the watcher gulp script the component content ist always the version of the script start.

**Comment by mikewheaton** [comment]
Same issue here. I'm not sure if it's related, but I'm getting this warning when I run `npm start`:

```
Failed to load external module @babel/register
```

**Comment by iRyusa** [comment]
@mikewheaton I think you're issue come from somewhere else, maybe your node version is too old but don't mix things, please open another ticket thanks
