### ISSUE TITLE
mjml-component-boilerplate  component registration is wrong

### ISSUE THREAD

**Issue by dschach1** [mjmlio/mjml-component-boilerplate#18]
.mjmlconfig

 {
   "packages": [
      "./lib/MjColumnImageText.js"
}

It should be 
{
    "./lib/MjBasicComponent.js",
    "./lib/MjImageText.js",
    "./lib/MjLayout.js"
   ]
 }

**Comment by kmcb777** [comment]
@dschach1 actually the .mjmlconfig is not needed here, the gulp task registers the components manually

**Comment by dschach1** [comment]
Sorry about the typo.  The change to .mjmlconfig.js is 
{
  "packages": [
    "./lib/MjBasicComponent.js",
    "./lib/MjImageText.js",
    "./lib/MjLayout.js"
  ]
}

**Comment by kmcb777** [comment]
Ah yes, the plugin probably uses its own instance of mjml, so components are not registered on this one by the gulp task.
If the plugin handles mjmlconfig then updating it would indeed solve the issue 👍
