### ISSUE TITLE
mjml-component-boilerplate validation fails for sample custom components with editor plugins

### ISSUE THREAD

**Issue by dschach1** [mjmlio/mjml-component-boilerplate#19]
Using vscode and the mjml plugin, there are validation errors viewing index.mjml

Removing
registerDependencies({
  // Tell the validator which tags are allowed as our component's parent
  'mj-hero': ['mj-basic-component'],
  'mj-column': ['mj-basic-component'],
  // Tell the validator which tags are allowed as our component's children
  'mj-basic-component': []
})

and then adding

  static dependencies = {
    // Tell the validator which tags are allowed as our component's parent
    'mj-hero': ['mj-basic-component'],
    'mj-column': ['mj-basic-component'],
    // Tell the validator which tags are allowed as our component's children
    'mj-basic-component': []
  }

to MjBasicComponent.js fixes the problem.

**Comment by dschach1** [comment]
The issue I found is in mjmlconfig.js in mjml-core. See
https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/helpers/mjmlconfig.js#L78

on line 78
registerDependencies((requiredComp.default || requiredComp).dependencies)

The code is looking for the dependencies member which is missing from the custom component.

**Comment by iRyusa** [comment]
My bad I haven't seen that part, I think we could rely on that here too then 🤔 cc @kmcb777
