### ISSUE TITLE
mjml-boilerplate with 3.2.2 beta

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml-component-boilerplate#2]
Moving here [this issue](https://github.com/mjmlio/mjml/issues/492) from @laslo89

is it possible to run the boilerplate with the latest beta version?
```
"mjml": "~3.2.0-beta.3",
"mjml-column": "~3.2.0-beta.2",
"mjml-core": "~3.2.0-beta.2",
"mjml-image": "~3.2.0-beta.2",
"mjml-section": "~3.2.0-beta.2",
"mjml-text": "~3.2.0-beta.2",
```
I added the latest version myself and modified a view things in the compile function inside the gulp file. 
I added the --output param
I added error notification 
 see below:

```
const compile = () => {
  gulp.src('components/**.js')
    .pipe(babel())
    .pipe(gulp.dest('lib'))
    .on('end', () => exec(
      './node_modules/.bin/mjml index.mjml --output index.html',
      (err, stdout, stderr) => {
                // NOTE: logs errors of gulp (we think at least)
                if (err) {
                    console.log('ERROR:\n', err); // eslint-disable-line no-console
                }

                // NOTE: logs the error message of our own code
                if (stdout && stdout.trim()) {
                    console.log('CODE INFO:\n', stdout); // eslint-disable-line no-console
                }

                if (stderr) {
                    console.log('CODE ERROR:\n', stderr); // eslint-disable-line no-console
                }
            }
    ));
}
```
when i run npm run build i run into this error:

```
ERROR:
 { [Error: Command failed: /bin/sh -c node_modules/.bin/mjml index.mjml --output index.html
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node_modules/.bin/mjml index.mjml --output index.html' }
CODE INFO:
 Error: EISDIR: illegal operation on a directory, open './'
    at Error (native)
```

I saw some changes in the cli, which i think are causing that error, but i couldn't relate them exactly. Maybe the boilerplate has to adapt to the newer version?

**Comment by ngarnier** [comment]
I'll try to have a look at that today @laslo89

**Comment by ngarnier** [comment]
Hey @laslo89, sorry for the delay. 

I had a look and tried using the boilerplate with `mjml v3.2.0` (released this morning) along with your changes to the gulpfile and I'm not encountering any issue, so I can't reproduce your bug.

![](https://puu.sh/tod37/1737ad9b29.png)

I'll close but feel free to reopen if you still have an issue.

**Comment by Laslo89** [comment]
Hi @ngarnier , thanks for the response :-)
I've just tried it with the latest 3.2.0 version. I downloaded a new boilerplate.
Unfortunately the error still occurs. 
enclosed you can find my gulpfile package.json and .mjmlconfig

it would be great to have a look at them.

[myfiles.zip](https://github.com/mjmlio/mjml-component-boilerplate/files/708780/myfiles.zip)

thx Laslo

**Comment by ngarnier** [comment]
Hey @Laslo89 I'm sorry I actually miss your answer, are you still having this issue? I'm reoponing.

**Comment by Laslo89** [comment]
Hey @ngarnier 
No problem at all. With the new version 3.3.0 of mjml everthing is fine. Nethertheless, i am looking forward to 4.0. Keep up the good Work. The boilerplate is a great to tool to build on!

**Comment by ngarnier** [comment]
Glad to hear it's solved, thanks for the anwer @Laslo89!
