### ISSUE TITLE
`ReferenceError: jsonToXML is not defined` when using children within component

### ISSUE THREAD

**Issue by highri5e** [mjmlio/mjml-component-boilerplate#22]
I'm trying to use <mj-layout> component with children inside, like this:

```
    <mj-layout>
      <mj-section>
        <mj-column></mj-column>
      </mj-section>
    </mj-layout>
```

When compiling I get the above error in `node_modules\mjml-core\lib\helpers\jsonToXML.js:19`
This is the line in question.

`var subNode = children && children.length > 0 ? children.map(jsonToXML).join('\n') : content ? content : '';`

The code works only if I remove `<mj-column></mj-column>`

**Comment by iRyusa** [comment]
Can you give a bit of details (mjml version used ? mj-layout code ?)

**Comment by highri5e** [comment]
The code I'm using is just the cloned boilerplate repo so the version of mjml is as was in `package.json` which is `"mjml": "^4.0.0"`
I have added mj-section and mj-column to `registerDependencies` in mj-layout. This is the only modification:

```
registerDependencies({
  // Tell the validator which tags are allowed as our component's children
  'mj-layout': [
    'mj-accordion',
    'mj-button',
    'mj-carousel',
    'mj-divider',
    'mj-html',
    'mj-image',
    'mj-raw',
    'mj-social',
    'mj-spacer',
    'mj-table',
    'mj-text',
    'mj-navbar',
    'mj-section',
    'mj-column'
  ],
  // Now tell the validator which tags are allowed as our component's parent
  'mj-wrapper': ['mj-layout'],
  'mj-body': ['mj-layout'],
})
```

The above error happens when I run the `gulp build` after modifying `index.mjml` like this.

```
<mj-layout>
      <mj-section>
        <mj-column></mj-column>
      </mj-section>
</mj-layout>
```

I didn't get as far as actually using the component outside of this boilerplate and honestly wouldn't know how to do it. I have not seen any documentation on this.

**Comment by iRyusa** [comment]
Can you do a `npm list mjml` to check the actual installed version please ? I think 4.4.0-beta has this issue and was resolved on release

**Comment by highri5e** [comment]
Here's the output:

```
$ npm list mjml
test@1.0.1 C:\Users\p\dev\mjml\layout
`-- mjml@4.0.3
```

**Comment by highri5e** [comment]
I've updated mjml to `4.4.1` and it works as expected.
