### ISSUE TITLE
npm install generates errors

### ISSUE THREAD

**Issue by AndyBaird** [mjmlio/mjml-component-boilerplate#25]
Running `npm install` on a fresh clone generates tons of errors making the boilerplate not usable. Here are the first errors that occur:

`node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v67-darwin-x64.tar.gz`

`node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)`

`node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v67-darwin-x64.tar.gz`

`node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)`

**Comment by iRyusa** [comment]
Most likely a version that was removed, we need to check this #24 first it might be a duplicate issue

For now you can maybe remove the lockfile and it should work
