### ISSUE TITLE
defaultAttributes doesn't work for attribute "padding"

### ISSUE THREAD

**Issue by Best40hahaha** [mjmlio/mjml-component-boilerplate#30]
Hi,

This is the first time creating my custom mjml component. I meet the issue when I want to expose an attribute named "padding" for my component. The basic description for the issue is the default value for "padding" doesn't work. My component is as below:
```
import { registerDependencies } from 'mjml-validator'
import { BodyComponent } from 'mjml-core'

registerDependencies({
    // Tell the validator which tags are allowed as our component's parent
    'mj-body': ['mj-gb-button'],
    // Tell the validator which tags are allowed as our component's children
    'mj-gb-button': []
})

export default class MjGBButton extends BodyComponent {
    static endTag = true;
    static allowedAttributes = {
        'href': 'string',
        'padding': 'unit(px){4}'
    }

    static defaultAttributes = {
        'href': 'www.google.com',
        'padding': '30px 0px'
    }

    render() {
        return this.renderMJML(`<mj-section>
        <mj-column width="100%">
          <mj-button  ${this.htmlAttributes({
              href:this.getAttribute('href'),
              padding:this.getAttribute('padding')
          })}>
            ${this.getContent()}
          </mj-button>
        </mj-column>
      </mj-section>`)
    }
}
```
In index.mjml, the code is like:
```
<mjml>
  <mj-body>
    <mj-gb-button>test</mj-gb-button>
  </mj-body>
</mjml>
```
I didn't write any attribute and expect the padding could be "30px 0px", but actually nothing happens("0px") shown on my chrome.  However, when I renamed "padding" to some "less standard name" such as "test-padding", the default attribute works perfectly well - shown "30px 0px" on my chrome browser. 

Feel free to tell me if there's something wrong within my code since it's my first time writing custom components.

Finally, some related version information is as below:
Microsoft Windows [Version 10.0.18363.900]
Chrome [version:  83.0.4103.116]
For the npm dependencies, they are all installed according to the package.json

Thank you very much for your help!

**Comment by iRyusa** [comment]
Sorry about the delay, I don't have notification on this repo.

It seems to work fine on 4.7.1 padding is applied to the `td` as expected
