### ISSUE TITLE
How to authorize registering the dependencies of my component?

### ISSUE THREAD

**Issue by Bartiff** [mjmlio/mjml-component-boilerplate#38]
I'm not sure I understand the `static dependencies` property. When I comment out this property in all the sample components (MjBasicComponent, MjImageText and MjLayout) and run `gulp build` it doesn't change the HTML output.

What am I not understanding?

I want to create a component that can be allowed in an `mj-text` but I can't.

**Comment by iRyusa** [comment]
`dependencies` is just a hint for linter. 

> I want to create a component that can be allowed in an mj-text but I can't.

`mj-text` is a content tag so you can't have any MJML inside it.
