### ISSUE TITLE
HTML isn't rendered on Windows

### ISSUE THREAD

**Issue by adamjw3** [mjmlio/mjml-component-boilerplate#4]

**Comment by adamjw3** [comment]
I've followed the instuctions and have no errors when running npm start. the components file gets created but no index.html to view the component.

**Comment by ngarnier** [comment]
hey @adamjw3, the file is compiled at the root of the project, so in the folder `mjml-component-boilerplate/`.

Can you please provide the output of those prompts in your terminal when you're working on the project?

- `pwd` (or `echo %cd%` on Windows)
- `ls` (or `dir` on Windows)

**Comment by adamjw3** [comment]
Hi

I'm on windows and using webstorm IDE

C:\Users\Adam\Documents\development\MJML>echo %cd%
C:\Users\Adam\Documents\development\MJML

C:\Users\Adam\Documents\development\MJML>dir
 Volume in drive C has no label.
 Volume Serial Number is A487-1554

 Directory of C:\Users\Adam\Documents\development\MJML

14/03/2017  16:29    <DIR>          .
14/03/2017  16:29    <DIR>          ..
14/03/2017  15:33               100 .babelrc
14/03/2017  15:33               806 .editorconfig
14/03/2017  15:33               272 .eslintrc
14/03/2017  15:33                55 .gitignore
14/03/2017  16:37    <DIR>          .idea
14/03/2017  15:57                62 .mjmlconfig
14/03/2017  16:26    <DIR>          components
14/03/2017  16:25               712 gulpfile.babel.js
14/03/2017  16:29               554 index.mjml
14/03/2017  15:38    <DIR>          lib
14/03/2017  15:33             1,082 LICENSE
14/03/2017  16:23    <DIR>          node_modules
14/03/2017  15:33             1,133 package.json
14/03/2017  15:33               546 README.md
              10 File(s)          5,322 bytes
               6 Dir(s)  256,270,381,056 bytes free

**Comment by ngarnier** [comment]
Ok... surprising. Can you please try to run `npm run build` and share the output as well?

**Comment by adamjw3** [comment]
yeah sure, its

C:\Users\Adam\Documents\development\MJML>npm run build

> test@1.0.1 build C:\Users\Adam\Documents\development\MJML
> gulp build

[17:40:37] Requiring external module babel-register
[17:40:38] Using gulpfile ~\Documents\development\MJML\gulpfile.babel.js
[17:40:38] Starting 'build'...
[17:40:38] Finished 'build' after 13 ms

> MJML compilation finished

C:\Users\Adam\Documents\development\MJML>

**Comment by ngarnier** [comment]
Honestly it's really hard to figure out what is happening here... Can you try, still in the boilerplate folder: 
```
> ./node_modules/.bin/mjml index.mjml
> ls
```

If `index.html` is still not here, I really don't know what's happening. Maybe you can join the MJML Slack so we debug together more easily? https://slack.mjml.io/

**Comment by adamjw3** [comment]
No still nothing. Could it be a pc issue? will get someone to try on a mac.

FYI I'm using the following npm and node versions

npm -v 4.4.1
node -v 6.10.0

I've attached the project including all the node modules
[MJML.zip](https://github.com/mjmlio/mjml-component-boilerplate/files/843955/MJML.zip)

**Comment by ngarnier** [comment]
After more investigation, it seems command prompt on Windows doesn't like much the relative paths. Here are two solutions: 

- Stop using command prompt and prefer [Bash on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) or [Git Bash](https://git-for-windows.github.io/), because, well... bash!
- If you still want to use command prompt, replace all the relative paths in [gulpfile.babel.js](https://github.com/mjmlio/mjml-component-boilerplate/blob/master/gulpfile.babel.js) and [.mjmlconfig](https://github.com/mjmlio/mjml-component-boilerplate/blob/master/.mjmlconfig) by absolute paths to your project

Thanks @adamjw3 for reporting and helping to solve this

**Comment by ngarnier** [comment]
Something identified with other Windows users, seems like replacing all the relative paths in gulpfile.babel.js and .mjmlconfig by absolute paths is the go-to solution for now.

**Comment by ngarnier** [comment]
Fixed by #7
