### ISSUE TITLE
Mjml component not rendering as html. More explicit requirements for custom components?

### ISSUE THREAD

**Issue by AveryTheDev** [mjmlio/mjml-component-boilerplate#46]
I pulled this repo and tried making a custom component following the examples but I had a few questions about exact requirements. I also wanted to know what if anything was wrong with this specific component that I've made

Questions: 

- Do the class components require "Mj" in its name or for the components themselves require "mj-" as a prefix? When I changed the names of the existing examples, they no longer worked and was wondering if there were any other naming specifics I may have missed. If this is a required detail, I believe it should be added to the documentation as people would normally name their components starting with their company/project name or whatever the component is tied to.
- What does it mean when the mjml shows up in html document but does not render as html? Can someone tell me where I have gone wrong?

For my example below, I've made a component called `mj-copy-category` that is supposed to render a table cell. Instead it returns nothing. 

<img width="662" alt="Screen Shot 2021-09-13 at 10 18 20 AM" src="https://user-images.githubusercontent.com/23192489/133100268-c60dba5b-71e4-46ba-afa0-8af959a762d2.png">

----

Steps I have taken to register this component have been:

1. Create and name component with Mj in its component name as well as its reference tag within the component folder.
2. Write code for the component as such. I used the Basic Component example as a reference as I am only passing in the text with the intent to return a styled table cell with this component

```js
import { BodyComponent } from 'mjml-core'

export default class MjCopyCategory extends BodyComponent {
  static endingTag = true

//only parents are 'tr'
  static dependencies = {
    'mj-copy-category': [],
  }

  // Tells the validator which attributes are allowed for mj-layout
  static allowedAttributes = {
    color: 'color',
    'font-size': 'unit(px)',
    'font-family': 'string',
  }

  // What the name suggests. Fallback value for this.getAttribute('attribute-name').
  static defaultAttributes = {
    color: '#6A6A88',
    'font-size': '15px',
    'font-family': '"Helvetica"',
  }

  getStyles() {
    return {
      copyKey: {
        color: this.getAttribute('color'),
        'font-size': this.getAttribute('font-size'),
        'font-family': this.getAttribute('font-family'),
      },
    }
  }

  render() {
    return `
        <td
        ${this.htmlAttributes({
          class: this.getAttribute('css-class'),
          style: 'copyKey',
        })}
        >
        ${this.getContent()}
        </td>
      `
  }
}
```

3. Run the `gulp build` script
4. Write a reference to the component's lib file in the `.mjmlconfig` file
5. Place the component `mj-copy-category` within the index.mjml file

```
<mjml>
  <mj-body>
    <!-- The first component, mj-basic-component renders as a column child -->
    <mj-section>
      <mj-column>
        <mj-basic-component color="green"> I'm among stars </mj-basic-component>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-table>
          <tr>
            <mj-copy-category>Report Thing</mj-copy-category>
          </tr>
        </mj-table>
      </mj-column>
    </mj-section>
    <!-- The second component, mj-image-text renders as a section -->
    <mj-image-text
      background-color="#DD685B"
      image-src="https://mjml.io/assets/img/mjml-logo.png"
      image-width="100px"
      font-size="24px"
      image-position="left"
    >
      MJML rules! hello modified
    </mj-image-text>

    <!-- The third component, mj-layout, also renders as a section -->
    <mj-layout>
      <mj-text color="pink" font-size="10px"> A super nice layout component </mj-text>
    </mj-layout>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
When you register a component it just transform the class name into kebab case. As mj-table is an ending tag it cannot receive any MJ component and only HTML that's why it doesn't work

**Comment by AveryTheDev** [comment]
So does this mean we cannot make mjml components that would go inside tables? Thats disappointing as that would clean up my code a lot, but if thats not how it works I understand. 

Thank you for clarifying this for me

**Comment by AveryTheDev** [comment]
And we cannot use regular "table" tags in mjml, so I do not have an alternative regarding my issue @iRyusa ?

**Comment by iRyusa** [comment]
Well the parser need to stop parsing at some point and we don't want to parse HTML (because sometime HTML for email can contain invalid HTML/ or templating related stuff). You won't really gain much to setup a whole custom component for something you can do with a standard css class here.
If you really need a component for that then you might want todo a custom "mj-table" that is not a ending tag and do the whole tr/td etc in MJML components. I wouldn't recommend it but you can

**Comment by AveryTheDev** [comment]
Sounds fair, I'll look into alternatives as far as names and go from there. Thanks for your help!
