### ISSUE TITLE
(mj-column-image-text) — Attribute text is illegal

### ISSUE THREAD

**Issue by PatriotRDX** [mjmlio/mjml-component-boilerplate#5]
Platform: OS X 10.12.3
Program: Terminal

Build states the attribute "text" included on the mj-column-image-text is illegal, although the compile works and completes. This is not a critical problem, but I thought you might want to know in case this is not the expected behavior.

Compiling the build, I get the following output:

```bash
> test@1.0.1 build /Users/wallace.638/Documents/Emails
> gulp build

[16:42:21] Requiring external module babel-register
[16:42:21] Using gulpfile ~/Documents/Emails/gulpfile.babel.js
[16:42:21] Starting 'build'...
[16:42:21] Finished 'build' after 9.51 ms
File: index.mjml 
Line 12 (mj-column-image-text) — Attribute text is illegal

> MJML compilation finished
```

NOTE: It only says line 12 and not 15 because I adjusted spacing in the .mjml file. I tried without adjusting the spacing (shouldn't matter) and got the same.

**Comment by Djibdjib** [comment]
Hi ! i have the same problem... Need help !

**Comment by ngarnier** [comment]
Hey @PatriotRDX, thanks for reporting. This is totally normal, as mj-column-image-text is not a standard component, the validation package doesn't recognize its attributes.

@Djibdjib Please open a different issue with your problem and we'll help you!
